project: "scRNA-VAE"
architecture: "VAE"
dataset: "scRNA-2k"
input_dim: 32738
latent_dim: 100
hidden_dims: [256, 128, 64]
learning_rate: 3e-4
batch_size: 32
epochs: 20  # not interested in training
reconstruction_dist: "poisson"