project: "scRNA"
architecture: "VAE"
dataset: "scRNA-2k"
input_dim: 32738
latent_dim: 100
hidden_dims: [256, 128]
learning_rate: 3.0e-4
batch_size: 64
epochs: 20  # not interested in training
reconstruction_dist: "poisson"